### PR TITLE
Add prefix/suffix to Group

### PR DESCRIPTION
**Pull request by kdmsnr**
Because I'd like to support ieee csl style someday:

ieee.csl

```
  <!-- Citation -->
  <citation collapse="citation-number">
    <sort>
      <key variable="citation-number"/>
    </sort>
    <layout delimiter=", ">
      <group prefix="[" suffix="]" delimiter=", ">
        <text variable="citation-number"/>
        <text macro="citation-locator"/>
      </group>
    </layout>
  </citation>
```

### CODE REVIEW

**Comment by inukshuk** [comment]
I don't think this is necessary? Affixes on group notes are definitely supported, e.g., [this test case](https://github.com/inukshuk/citeproc-ruby/blob/master/features/renderer.feature#L26).

**Comment by kdmsnr** [comment]
Thank you. I misunderstood.

BTW, it cannot parse " <text macro="citation-locator"/>", so how about use warn or something instead of raise

```
       def macro
-        raise "failed to resolve macro #{attributes[:macro].inspect}" unless
-          !root? && root.respond_to?(:macros)
-
-        root.macros[attributes[:macro]]
+        if !root? && root.respond_to?(:macros)
+          root.macros[attributes[:macro]]
+        else
+          # warn "failed to resolve macro #{attributes[:macro].inspect}"
+        end
       end
```

**Comment by inukshuk** [comment]
How are you parsing this? I agree that parsing the node should not produce an error (not even a warning actually) -- but trying to access the macro (i.e., trying to render the node) should absolutely raise an error if the node is detached.

**Comment by kdmsnr** [comment]
I've added a test case to the `citeproc-ruby/features/renderer.feature`
(I know the citation-number is not supported yet)


```diff
+  Scenario: Date Group Rendering
+    Given the following style node:
+      """
+      <group prefix="[" suffix="]" delimiter=", ">
+        <text variable="citation-number"/>
+        <text macro="citation-locator"/>
+      </group>
+      """
+    When I render the following citation items as "text":
+      | citation-number  |
+      | 1                |
+      | 2                |
+    Then the results should be:
+      | [1]              |
+      | [2]              |
```

**Comment by kdmsnr** [comment]
Ah, I think I made a mistake to set a fragment of xml. I should have done like this:

```
    Given the following style node:
      """
  <macro name="citation-locator">
    <group delimiter=" ">
      <choose>
        <if locator="page">
          <label variable="locator" form="short"/>
        </if>
        <else>
          <label variable="locator" form="short" text-case="capitalize-first"/>
        </else>
      </choose>
      <text variable="locator"/>
    </group>
  </macro>
  <!-- Citation -->
  <citation collapse="citation-number">
    <sort>
      <key variable="citation-number"/>
    </sort>
    <layout delimiter=", ">
      <group prefix="[" suffix="]" delimiter=", ">
        <text variable="citation-number"/>
        <text macro="citation-locator"/>
      </group>
    </layout>
  </citation>
```

**Pull request closed without merging**
